/**
 * auto-update.ts -- Electron auto-update module.
 *
 * Why generic provider: BPT is distributed via internal network (SVN + file server).
 * Standard GitHub Releases won't work for internal tools. electron-updater's
 * generic provider supports any HTTP server hosting release assets.
 *
 * Configure by setting `updateServerUrl` in BPT settings to your internal
 * file server URL (e.g., http://internal-server/bpt-releases/).
 * The server must host latest.yml (auto-generated by electron-builder)
 * alongside the packaged app files.
 *
 * If no URL is configured, auto-update is silently disabled.
 */

import { BrowserWindow } from 'electron';
import { getConfig } from '../core/config';
import { logger } from '../core/logger';

// electron-updater is an optional dependency — may not be installed in dev
let autoUpdater: typeof import('electron-updater').autoUpdater | null = null;

async function loadUpdater(): Promise<boolean> {
  try {
    const mod = await import('electron-updater');
    autoUpdater = mod.autoUpdater;
    return true;
  } catch {
    logger.info('updater', 'electron-updater not available (dev mode)');
    return false;
  }
}

function notifyRenderer(
  getWindow: () => BrowserWindow | null,
  event: Record<string, unknown>,
): void {
  const win = getWindow();
  if (win && !win.isDestroyed()) {
    win.webContents.send('updater:event', event);
  }
}

/**
 * Initialize auto-update. Call once from main.ts after window creation.
 * No-op if updateServerUrl is not configured or electron-updater is missing.
 */
export async function initAutoUpdate(
  getWindow: () => BrowserWindow | null,
): Promise<void> {
  const updateUrl = getConfig('updateServerUrl') as string;
  if (!updateUrl) {
    logger.info('updater', 'No update server URL configured, auto-update disabled');
    return;
  }

  const loaded = await loadUpdater();
  if (!loaded || !autoUpdater) return;

  autoUpdater.setFeedURL({
    provider: 'generic',
    url: updateUrl,
  });

  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = true;

  autoUpdater.on('checking-for-update', () => {
    logger.info('updater', 'Checking for update...');
    notifyRenderer(getWindow, { type: 'checking' });
  });

  autoUpdater.on('update-available', (info) => {
    logger.info('updater', 'Update available', { version: info.version });
    notifyRenderer(getWindow, { type: 'available', version: info.version });
  });

  autoUpdater.on('update-not-available', () => {
    logger.info('updater', 'No updates available');
    notifyRenderer(getWindow, { type: 'not-available' });
  });

  autoUpdater.on('download-progress', (progress) => {
    notifyRenderer(getWindow, {
      type: 'progress',
      percent: Math.round(progress.percent),
    });
  });

  autoUpdater.on('update-downloaded', (info) => {
    logger.info('updater', 'Update downloaded', { version: info.version });
    notifyRenderer(getWindow, { type: 'downloaded', version: info.version });
  });

  autoUpdater.on('error', (err) => {
    logger.error('updater', 'Update error', { error: err.message });
    notifyRenderer(getWindow, { type: 'error', error: err.message });
  });

  // Check after 10-second delay to avoid blocking boot
  setTimeout(() => {
    autoUpdater?.checkForUpdates().catch((err: Error) => {
      logger.error('updater', 'Initial update check failed', { error: err.message });
    });
  }, 10_000);
}

/** Manually trigger an update check. */
export function checkForUpdates(): Promise<void> {
  if (!autoUpdater) return Promise.resolve();
  return autoUpdater.checkForUpdates().then(() => {});
}

/** Download a discovered update. */
export function downloadUpdate(): Promise<void> {
  if (!autoUpdater) return Promise.resolve();
  return autoUpdater.downloadUpdate().then(() => {});
}

/** Quit and install the downloaded update. */
export function installUpdate(): void {
  if (!autoUpdater) return;
  autoUpdater.quitAndInstall(false, true);
}
