"""知识文件清点（KB 覆盖哨兵与 OKF 生成器的共用真相源）。

「哪些文件算知识文件」此前只写在 tests/test_kb_coverage_sentinel.py 里；
生成器落存量清单（coverage_inventory，2026-07-27 守密人裁定的哨兵两档制）
需要同一份 glob——抄一份必漂移，故下沉到此，两侧 import。

两档制语义（谁在什么时候该红）：
- 清单内（上次 OKF 重建时点已存在的知识文件）未被任何概念覆盖 = 生成器
  见过它仍没接住 = **真「假完备」，硬红**；
- 清单外（重建之后才新增的文件）未覆盖 = §6.1 协议内的正常时差（合并 main
  后 push 触发器数分钟内自动重建收编），**软报不红**——但下一次重建会把它
  收进清单，届时仍未覆盖就硬红：洞最多活一个重建周期，不会永久隐身。
"""
from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

# 应被知识库覆盖的「知识文件」glob（相对仓根）。纯代码/生成物/瞬态不在内。
KNOWLEDGE_GLOBS = [
    "assets/data/*.json", "assets/data/*.md",
    "assets/data/character-personas/*.json", "assets/data/character-personas/*.md",
    "memory/*.md", "memory/*.json",
    "memory/active/*.md", "memory/research/*.md", "memory/strategy/*.md",
    "projects/wiki/data/processed/*.json", "projects/wiki/data/processed/*.md",
    "projects/wiki/data/processed/story/*.json", "projects/wiki/data/processed/story/*.md",
    "projects/wiki/data/schemas/*.json",
    "projects/news/index/community_index.json",
    "projects/news/output/*-latest.json",
    "Public-Info-Pool/Resource/*/*.md",
    # 子项目上下文用 glob，不逐个点名——原先五条硬编码把 silver-core-maestro-sdk /
    # silver-core-testbed 的 CONTEXT.md 挡在「知识文件」定义之外，于是覆盖哨兵
    # （test_kb_coverage_sentinel）对这两份从未进过知识库的必读档案**结构上不可能报红**：
    # 哨兵只检查它自己列出来的文件，漏在清单里的洞它一辈子看不见。
    "projects/*/CONTEXT.md",
    "projects/silver-core-sdk/docs/*.md",
    "projects/site/design/*.html", "projects/site/design/*.css",
]
# 单列的顶层知识文件
KNOWLEDGE_FILES = ["CLAUDE.md", "README.md", "RELEASES.md"]

# 清单落点（okf/ 内，随重建 CI 一并提交）。
INVENTORY_PATH = "okf/coverage_inventory.json"


def collect_knowledge_files(repo: Path) -> set[str]:
    """当前树上的全部知识文件（仓根相对 posix 路径）。"""
    out: set[str] = set()
    for g in KNOWLEDGE_GLOBS:
        for p in repo.glob(g):
            if p.is_file():
                out.add(p.relative_to(repo).as_posix())
    for f in KNOWLEDGE_FILES:
        if (repo / f).exists():
            out.add(f)
    return out


def write_inventory(repo: Path, bundle: Path | None = None) -> Path:
    """把当前树的知识文件存量落为清单（仅供 OKF 重建末尾调用——清单的语义
    是「重建时点的存量」，重建之外的场合不得刷新它，否则新文件会被错误地
    划进硬红档）。`bundle` 允许生成器把落点跟随其（可能被测试重定向的）
    BUNDLE 目录——否则单测里 bok.main() 会把清单写进真 okf/ 污染工作树。"""
    dest = (bundle / "coverage_inventory.json") if bundle is not None else repo / INVENTORY_PATH
    dest.write_text(
        json.dumps(
            {
                "_meta": (
                    "knowledge-file inventory at the last OKF rebuild; the coverage "
                    "sentinel hard-fails uncovered files IN this list (the builder saw "
                    "them and still missed) and soft-reports files not yet in it "
                    "(added after the rebuild, pending the next one). Regenerated by "
                    "build_okf_bundle.py only."
                ),
                "files": sorted(collect_knowledge_files(repo)),
            },
            ensure_ascii=False,
            indent=1,
        )
        + "\n",
        encoding="utf-8",
    )
    return dest


def read_inventory(repo: Path) -> set[str] | None:
    """读清单；不存在返回 None（哨兵回退旧全严格行为）。"""
    p = repo / INVENTORY_PATH
    if not p.exists():
        return None
    return set(json.loads(p.read_text(encoding="utf-8"))["files"])
